version: '3.9'

services:
  db:
    image: postgres
    container_name: db-persons
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
    #  - db-data:/var/lib/postgresql/data
      - .:/app
    ports:
      - 5432:5432
    networks:
      - backend

#volumes:
#  db-data:
